### ISSUE TITLE
Hotkey hasn't worked for couple patches now

### ISSUE THREAD

**Issue by DelVision** [ChrisScott9456/runelite-rooftoggle#2]
Basically hotkey just doesn't do anything anymore, it used to work when the plugin was brand new but now there's no reaction even with the default key.

Possibly was broken when Jagex added bunch of new options to the settings

**Comment by ChrisScott9456** [comment]
> Basically hotkey just doesn't do anything anymore, it used to work when the plugin was brand new but now there's no reaction even with the default key.
> 
> Possibly was broken when Jagex added bunch of new options to the settings

Thanks for the notice. I'll take a look as soon as I have some time.

**Comment by ChrisScott9456** [comment]
Resolved in commit 7f73a0165500dd0d66d070515369b9ea2798f5d5
